openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/company/{company_number}/:
    get:
      operationId: company_retrieve
      parameters:
      - in: path
        name: company_number
        schema:
          type: string
          pattern: ^\w+$
        required: true
      tags:
      - company
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyProfile'
          description: ''
  /api/company/{company_number}/officers/:
    get:
      operationId: company_officers_retrieve
      parameters:
      - in: path
        name: company_number
        schema:
          type: string
          pattern: ^\w+$
        required: true
      tags:
      - company
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /api/company/{company_number}/registered-office-address/:
    get:
      operationId: company_registered_office_address_retrieve
      parameters:
      - in: path
        name: company_number
        schema:
          type: string
          pattern: ^\w+$
        required: true
      tags:
      - company
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisteredOfficeAddress'
          description: ''
  /api/search/companies/:
    get:
      operationId: search_companies_retrieve
      tags:
      - search
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    CompanyProfile:
      type: object
      properties:
        address_snippet:
          type: string
          nullable: true
        company_name:
          type: string
        company_number:
          type: string
        company_status:
          type: string
          nullable: true
        date_of_cessation:
          type: string
          format: date
        date_of_creation:
          type: string
          format: date
          nullable: true
        type:
          type: string
        sic_codes:
          type: array
          items:
            type: string
        registered_office_address:
          $ref: '#/components/schemas/RegisteredOfficeAddress'
      required:
      - company_name
      - company_number
      - registered_office_address
      - type
    RegisteredOfficeAddress:
      type: object
      properties:
        address_line_1:
          type: string
        address_line_2:
          type: string
        country:
          type: string
        locality:
          type: string
        po_box:
          type: string
        postal_code:
          type: string
        region:
          type: string
        care_of:
          type: string
        premises:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: chsearch_session_id
