version: 2

# Machines configs
machine_python3_postgres: &machine_python3_postgres_redis
  docker:
    - image: cimg/python:3.9.5
    - image: cimg/postgres:12.8
      environment:
        POSTGRES_USER: debug
        POSTGRES_PASSWORD: debug
        POSTGRES_DB: directory_ch_search_debug
    - image: cimg/redis:7.2.4
    - image: opensearchproject/opensearch:1.2.2
      ports: ["9200:9200"]
      environment:
        # Run in development mode to ignore bootstrap checks
        transport.host: "localhost"
        # opensearch configuration
        discovery.type: "single-node"
        plugins.security.disabled: "true"


# Individual (shared) steps.
step_checkout_repo: &step_checkout_repo
  checkout


jobs:
  test:
    <<: *machine_python3_postgres_redis
    steps:
      - *step_checkout_repo
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: v2-deps-{{ checksum "requirements_test.txt" }}
      - run:
          name: Create virtualenv and install dependencies
          command: |
            rm -rf venv && python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements_test.txt
      - save_cache:
          key: v2-deps-{{ checksum "requirements_test.txt" }}
          paths:
            - "venv"
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Install psql
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make pytest
            make pytest_codecov
  flake8:
    docker:
      - image: circleci/python:3.9
    steps:
      - *step_checkout_repo
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8
            flake8 . --exclude=migrations,venv

workflows:
  version: 2
  test:
    jobs:
      - test
      - flake8
